yaml-files:
  - '*.yaml'
  - '*.yml'

# https://yamllint.readthedocs.io/en/stable/configuration.html
extends: default

ignore-from-file:
  - .gitignore
  - semantic-layer/.yamlignore

rules:
  line-length: disable
  document-start: disable
  comments:
    level: error
  comments-indentation:
    level: error
  truthy:
    level: error
